import React,{useMemo,useState}from"react";import{useNavigate}from"react-router-dom";
const API_BASE=(import.meta.env.VITE_API_BASE||"http://localhost:4000").replace(/\/$/,"");
const categories=[{value:"female-wear",label:"Women’s wear"},{value:"kids-wear",label:"Kids’ wear"},{value:"artificial-jewellery",label:"Artificial jewellery"}];
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,"").replace(/\s+/g,"-").replace(/-+/g,"-");
const empty={title:"",slug:"",category:"female-wear",subcategory:"",audience:"women",price:"",mrp:"",stock:"0",description:"",isFeatured:false,isNewArrival:true};
const mediaFromUrls=(value:string)=>value.split(/\r?\n/).map(url=>url.trim()).filter(Boolean).map(url=>({type:/\.(mp4|webm|mov)(\?|$)/i.test(url)?"video":"image",url}));
export default function AddProduct(){const navigate=useNavigate();const[form,setForm]=useState(empty);const[files,setFiles]=useState<File[]>([]);const[mediaUrls,setMediaUrls]=useState("");const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const update=(name:string,value:string|boolean)=>setForm(c=>({...c,[name]:value}));const previews=useMemo(()=>files.map(file=>({name:file.name,type:file.type,url:URL.createObjectURL(file)})),[files]);
async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const body=new FormData();Object.entries(form).forEach(([k,v])=>body.append(k,String(v)));body.append("mediaUrls",JSON.stringify(mediaFromUrls(mediaUrls)));files.forEach(file=>body.append("mediaFiles",file));const response=await fetch(`${API_BASE}/admin/products`,{method:"POST",body});if(!response.ok)throw new Error((await response.json()).message||"Product save nahi ho saka.");navigate("/products")}catch(error){setMessage(error instanceof Error?error.message:"Product save nahi ho saka.")}finally{setSaving(false)}}
return <div className="adminPage"><div className="pageTitle"><div><h2>Add a new product</h2><p>Three simple sections—basic details, pricing and product media.</p></div></div><form className="adminForm easyProductForm" onSubmit={submit}>
<section className="formSection"><div className="formSectionTitle"><span>1</span><div><strong>Product details</strong><small>Tell customers what you are selling</small></div></div><label>Product name<input value={form.title} placeholder="e.g. Floral cotton kurti" onChange={e=>{update("title",e.target.value);update("slug",slugify(e.target.value))}} required/></label><div className="formGrid"><label>Category<select value={form.category} onChange={e=>update("category",e.target.value)}>{categories.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label><label>Subcategory <small>(optional)</small><input value={form.subcategory} onChange={e=>update("subcategory",e.target.value)} placeholder="e.g. Kurtis"/></label></div><label>Description<textarea rows={4} value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Material, fit, colour and other useful details…"/></label></section>
<section className="formSection"><div className="formSectionTitle"><span>2</span><div><strong>Price and stock</strong><small>Set selling details</small></div></div><div className="formGrid three"><label>Selling price (₹)<input type="number" min="0" value={form.price} onChange={e=>update("price",e.target.value)} required/></label><label>MRP (₹) <small>(optional)</small><input type="number" min="0" value={form.mrp} onChange={e=>update("mrp",e.target.value)}/></label><label>Available stock<input type="number" min="0" value={form.stock} onChange={e=>update("stock",e.target.value)} required/></label></div></section>
<section className="formSection"><div className="formSectionTitle"><span>3</span><div><strong>Photos and video</strong><small>Select up to 10 files; first photo becomes the cover</small></div></div><label className="mediaDrop"><input type="file" accept="image/*,video/*" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,10))}/><strong>＋ Choose photos or product video</strong><small>JPG, PNG, WEBP, MP4 or WEBM · max 25 MB each</small></label>{previews.length>0&&<div className="mediaPreviewGrid">{previews.map((item,i)=><div key={item.url}>{item.type.startsWith("video")?<video src={item.url}/>:<img src={item.url} alt={item.name}/>}<span>{i===0&&item.type.startsWith("image")?"Cover · ":""}{item.name}</span></div>)}</div>}<label>Or paste image/video links <small>(one link per line)</small><textarea rows={3} value={mediaUrls} onChange={e=>setMediaUrls(e.target.value)} placeholder={'https://…/front.jpg\nhttps://…/product-video.mp4'}/></label></section>
<section className="publishOptions"><label className="checkLabel"><input type="checkbox" checked={form.isNewArrival} onChange={e=>update("isNewArrival",e.target.checked)}/><span><strong>Mark as New Arrival</strong><small>Shows a “New” badge and appears in New Arrivals</small></span></label><label className="checkLabel"><input type="checkbox" checked={form.isFeatured} onChange={e=>update("isFeatured",e.target.checked)}/><span><strong>Feature on homepage</strong><small>Include in the Raman edit section</small></span></label></section>
<input type="hidden" value={form.slug}/>{message&&<div className="errorMessage">{message}</div>}<div className="formActions"><button className="primaryButton" disabled={saving}>{saving?"Saving…":"Save and publish product"}</button><button type="button" onClick={()=>navigate("/products")}>Cancel</button></div></form></div>}
